//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelsAddin {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class ConfigurationsLastUsed : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigurationsLastUsed defaultInstance = ((ConfigurationsLastUsed)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigurationsLastUsed())));
        
        public static ConfigurationsLastUsed Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigureAreaUnitsLastUsedParams {
            get {
                return ((string)(this["ConfigureAreaUnitsLastUsedParams"]));
            }
            set {
                this["ConfigureAreaUnitsLastUsedParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportTraverseFileLastUsedParams {
            get {
                return ((string)(this["ExportTraverseFileLastUsedParams"]));
            }
            set {
                this["ExportTraverseFileLastUsedParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportParcelReportFileLastUsedParams {
            get {
                return ((string)(this["ExportParcelReportFileLastUsedParams"]));
            }
            set {
                this["ExportParcelReportFileLastUsedParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigureUpdateCOGOLastUsedParams {
            get {
                return ((string)(this["ConfigureUpdateCOGOLastUsedParams"]));
            }
            set {
                this["ConfigureUpdateCOGOLastUsedParams"] = value;
            }
        }
    }
}
