//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurvesAndLines {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class ConfigurationsLastUsed : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigurationsLastUsed defaultInstance = ((ConfigurationsLastUsed)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigurationsLastUsed())));
        
        public static ConfigurationsLastUsed Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigureSimplifyByTangentLastUsedParams {
            get {
                return ((string)(this["ConfigureSimplifyByTangentLastUsedParams"]));
            }
            set {
                this["ConfigureSimplifyByTangentLastUsedParams"] = value;
            }
        }
    }
}
